name: 'Tag version commit'
description: 'tagging commits whose title matches a version regex'
outputs:
  tag:
    description: 'The tag that has been created'
  commit:
    description: 'The commit that was tagged'
inputs:
  token:
    description: 'GitHub token, required for permission to create a tag'
    required: true
  version_regex:
    description: 'The version regex to use for detecting version in commit messages'
    required: false
    default: '[0-9]+.[0-9]+.[0-9]+'
  version_tag_prefix:
    description: 'A prefix to prepend to the detected version number to create the tag'
    required: false
    default: ''
  dry_run:
    description: 'Do everything except actually create the tag'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'tag'
  color: 'purple'
