name: 'test'
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm ci
        npm run all
  test-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm ci
        npm run build
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
